[project]
name = "auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "plotly>=6.0.1",
    "scipy>=1.15.2",
    "torch>=2.7.0",
    "torchio>=0.20.8",
]
